<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Project 2: Test CSV file Cleaning

### Contents:
- [Data Import and Cleaning](#Data-Import-and-Cleaning)
    - [Import Libraries](#Import-Libraries)
    - [Import CSV files](#Import-CSV-files)
    - [Check and clean up dataframes](#Check-and-clean-up-dataframes)
- [Export cleaned dataframe into CSV file](#Export-cleaned-dataframe-into-CSV-file)
- [Import cleaned CSV file](#Import-cleaned-CSV-file)
- [Dummify columns](#Dummify-columns)
- [Export dummified dataframe into CSV file](#Export-dummified-dataframe-into-CSV-file)

## Data Import and Cleaning

### Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn.model_selection import train_test_split, cross_val_score

import scipy.stats as stats

### Import CSV files

In [2]:
test = pd.read_csv('../data/test.csv')

test.head()

Id        PID  MS SubClass MS Zoning  Lot Frontage  Lot Area Street  \
0  2658  902301120          190        RM          69.0      9142   Pave   
1  2718  905108090           90        RL           NaN      9662   Pave   
2  2414  528218130           60        RL          58.0     17104   Pave   
3  1989  902207150           30        RM          60.0      8520   Pave   
4   625  535105100           20        RL           NaN      9500   Pave   

  Alley Lot Shape Land Contour  ... 3Ssn Porch Screen Porch Pool Area Pool QC  \
0  Grvl       Reg          Lvl  ...          0            0         0     NaN   
1   NaN       IR1          Lvl  ...          0            0         0     NaN   
2   NaN       IR1          Lvl  ...          0            0         0     NaN   
3   NaN       Reg          Lvl  ...          0            0         0     NaN   
4   NaN       IR1          Lvl  ...          0          185         0     NaN   

  Fence Misc Feature Misc Val Mo Sold  Yr Sold  Sale Type  
0   NaN          NaN        0       4     2006        WD   
1   NaN          NaN        0       8     2006        WD   
2   NaN          NaN        0       9     2006        New  
3   NaN          NaN        0       7     2007        WD   
4   NaN          NaN        0       7     2009        WD   

[5 rows x 80 columns]

### Check and clean up dataframes

In [3]:
#change all column names to lower case and replace ' ' with '_'
test.columns = test.columns.str.lower().str.replace(' ', '_')

test.head()

id        pid  ms_subclass ms_zoning  lot_frontage  lot_area street  \
0  2658  902301120          190        RM          69.0      9142   Pave   
1  2718  905108090           90        RL           NaN      9662   Pave   
2  2414  528218130           60        RL          58.0     17104   Pave   
3  1989  902207150           30        RM          60.0      8520   Pave   
4   625  535105100           20        RL           NaN      9500   Pave   

  alley lot_shape land_contour  ... 3ssn_porch screen_porch pool_area pool_qc  \
0  Grvl       Reg          Lvl  ...          0            0         0     NaN   
1   NaN       IR1          Lvl  ...          0            0         0     NaN   
2   NaN       IR1          Lvl  ...          0            0         0     NaN   
3   NaN       Reg          Lvl  ...          0            0         0     NaN   
4   NaN       IR1          Lvl  ...          0          185         0     NaN   

  fence misc_feature misc_val mo_sold  yr_sold  sale_type  
0   NaN          NaN        0       4     2006        WD   
1   NaN          NaN        0       8     2006        WD   
2   NaN          NaN        0       9     2006        New  
3   NaN          NaN        0       7     2007        WD   
4   NaN          NaN        0       7     2009        WD   

[5 rows x 80 columns]

In [4]:
test.columns = test.columns.str.lower().str.replace(' ', '_')

test.head()

id        pid  ms_subclass ms_zoning  lot_frontage  lot_area street  \
0  2658  902301120          190        RM          69.0      9142   Pave   
1  2718  905108090           90        RL           NaN      9662   Pave   
2  2414  528218130           60        RL          58.0     17104   Pave   
3  1989  902207150           30        RM          60.0      8520   Pave   
4   625  535105100           20        RL           NaN      9500   Pave   

  alley lot_shape land_contour  ... 3ssn_porch screen_porch pool_area pool_qc  \
0  Grvl       Reg          Lvl  ...          0            0         0     NaN   
1   NaN       IR1          Lvl  ...          0            0         0     NaN   
2   NaN       IR1          Lvl  ...          0            0         0     NaN   
3   NaN       Reg          Lvl  ...          0            0         0     NaN   
4   NaN       IR1          Lvl  ...          0          185         0     NaN   

  fence misc_feature misc_val mo_sold  yr_sold  sale_type  
0   NaN          NaN        0       4     2006        WD   
1   NaN          NaN        0       8     2006        WD   
2   NaN          NaN        0       9     2006        New  
3   NaN          NaN        0       7     2007        WD   
4   NaN          NaN        0       7     2009        WD   

[5 rows x 80 columns]

In [5]:
#checking number of rows and columns for dataframes
print('test dataframe (rows, columns) =', test.shape)

test dataframe (rows, columns) = (878, 80)


In [6]:
#set max viewable rows so displays will not be truncated
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 250)
np.set_printoptions(threshold=np.inf)

#checking for NULL values for train dataframe
test.isnull().sum()

id                   0
pid                  0
ms_subclass          0
ms_zoning            0
lot_frontage       160
lot_area             0
street               0
alley              820
lot_shape            0
land_contour         0
utilities            0
lot_config           0
land_slope           0
neighborhood         0
condition_1          0
condition_2          0
bldg_type            0
house_style          0
overall_qual         0
overall_cond         0
year_built           0
year_remod/add       0
roof_style           0
roof_matl            0
exterior_1st         0
exterior_2nd         0
mas_vnr_type         1
mas_vnr_area         1
exter_qual           0
exter_cond           0
foundation           0
bsmt_qual           25
bsmt_cond           25
bsmt_exposure       25
bsmtfin_type_1      25
bsmtfin_sf_1         0
bsmtfin_type_2      25
bsmtfin_sf_2         0
bsmt_unf_sf          0
total_bsmt_sf        0
heating              0
heating_qc           0
central_air          0
electrical 

In [7]:
#check datatypes of each column in train dataframe
test.dtypes

id                   int64
pid                  int64
ms_subclass          int64
ms_zoning           object
lot_frontage       float64
lot_area             int64
street              object
alley               object
lot_shape           object
land_contour        object
utilities           object
lot_config          object
land_slope          object
neighborhood        object
condition_1         object
condition_2         object
bldg_type           object
house_style         object
overall_qual         int64
overall_cond         int64
year_built           int64
year_remod/add       int64
roof_style          object
roof_matl           object
exterior_1st        object
exterior_2nd        object
mas_vnr_type        object
mas_vnr_area       float64
exter_qual          object
exter_cond          object
foundation          object
bsmt_qual           object
bsmt_cond           object
bsmt_exposure       object
bsmtfin_type_1      object
bsmtfin_sf_1         int64
bsmtfin_type_2      object
b

In [8]:
test.head()

id        pid  ms_subclass ms_zoning  lot_frontage  lot_area street  \
0  2658  902301120          190        RM          69.0      9142   Pave   
1  2718  905108090           90        RL           NaN      9662   Pave   
2  2414  528218130           60        RL          58.0     17104   Pave   
3  1989  902207150           30        RM          60.0      8520   Pave   
4   625  535105100           20        RL           NaN      9500   Pave   

  alley lot_shape land_contour utilities lot_config land_slope neighborhood  \
0  Grvl       Reg          Lvl    AllPub     Inside        Gtl      OldTown   
1   NaN       IR1          Lvl    AllPub     Inside        Gtl       Sawyer   
2   NaN       IR1          Lvl    AllPub     Inside        Gtl      Gilbert   
3   NaN       Reg          Lvl    AllPub     Inside        Gtl      OldTown   
4   NaN       IR1          Lvl    AllPub     Inside        Gtl        NAmes   

  condition_1 condition_2 bldg_type house_style  overall_qual  overall_cond  \
0        Norm        Norm    2fmCon      2Story             6             8   
1        Norm        Norm    Duplex      1Story             5             4   
2        Norm        Norm      1Fam      2Story             7             5   
3        Norm        Norm      1Fam      1Story             5             6   
4        Norm        Norm      1Fam      1Story             6             5   

   year_built  year_remod/add roof_style roof_matl exterior_1st exterior_2nd  \
0        1910            1950      Gable   CompShg      AsbShng      AsbShng   
1        1977            1977      Gable   CompShg      Plywood      Plywood   
2        2006            2006      Gable   CompShg      VinylSd      VinylSd   
3        1923            2006      Gable   CompShg      Wd Sdng      Wd Sdng   
4        1963            1963      Gable   CompShg      Plywood      Plywood   

  mas_vnr_type  mas_vnr_area exter_qual exter_cond foundation bsmt_qual  \
0         None           0.0         TA         Fa      Stone        Fa   
1         None           0.0         TA         TA     CBlock        Gd   
2         None           0.0         Gd         TA      PConc        Gd   
3         None           0.0         Gd         TA     CBlock        TA   
4      BrkFace         247.0         TA         TA     CBlock        Gd   

  bsmt_cond bsmt_exposure bsmtfin_type_1  bsmtfin_sf_1 bsmtfin_type_2  \
0        TA            No            Unf             0            Unf   
1        TA            No            Unf             0            Unf   
2        Gd            Av            GLQ           554            Unf   
3        TA            No            Unf             0            Unf   
4        TA            No            BLQ           609            Unf   

   bsmtfin_sf_2  bsmt_unf_sf  total_bsmt_sf heating heating_qc central_air  \
0             0         1020           1020    GasA         Gd           N   
1             0         1967           1967    GasA         TA           Y   
2             0          100            654    GasA         Ex           Y   
3             0          968            968    GasA         TA           Y   
4             0          785           1394    GasA         Gd           Y   

  electrical  1st_flr_sf  2nd_flr_sf  low_qual_fin_sf  gr_liv_area  \
0      FuseP         908        1020                0         1928   
1      SBrkr        1967           0                0         1967   
2      SBrkr         664         832                0         1496   
3      SBrkr         968           0                0          968   
4      SBrkr        1394           0                0         1394   

   bsmt_full_bath  bsmt_half_bath  full_bath  half_bath  bedroom_abvgr  \
0               0               0          2          0              4   
1               0               0          2          0              6   
2               1               0          2          1              3   
3               0               0        

#### Filling in the NA or empty cells with either 0 or no

Assume NA or empty cells has no such feature, therefore change the cell values to 0.0 or no to indicate this

In [9]:
#changing nan or empty cells to 0 for all relevant columns
test[['lot_frontage', 
       'mas_vnr_area', 
       'bsmtfin_sf_1', 
       'bsmtfin_sf_2']] = test[['lot_frontage', 
                                'mas_vnr_area', 
                                'bsmtfin_sf_1', 
                                'bsmtfin_sf_2']].fillna(0)

In [10]:
#changing nan or empty cells to no for all relevant columns
test[['alley', 
       'mas_vnr_type', 
       'bsmt_qual', 
       'bsmt_cond', 
       'bsmt_exposure', 
       'bsmtfin_type_1', 
       'bsmtfin_type_2', 
       'fireplace_qu', 
       'garage_type', 
       'garage_finish', 
       'garage_qual', 
       'garage_cond', 
       'pool_qc', 
       'fence', 
       'misc_feature']] = test[['alley', 
                                 'mas_vnr_type', 
                                 'bsmt_qual', 
                                 'bsmt_cond', 
                                 'bsmt_exposure', 
                                 'bsmtfin_type_1', 
                                 'bsmtfin_type_2', 
                                 'fireplace_qu', 
                                 'garage_type', 
                                 'garage_finish', 
                                 'garage_qual', 
                                 'garage_cond', 
                                 'pool_qc', 
                                 'fence', 
                                 'misc_feature']].fillna('no')


In [11]:
#1 empty cell for electrical column
#use deductive imputation to decide which value to replace empty cell with
#check for value that is most common in the column
print('Before filling the empty cell:\n', test['electrical'].value_counts())

#replace the empty cell with SBrkr, assuming it is of that value using deductive imputation
test['electrical'] = test['electrical'].fillna('SBrkr')

print('\nAfter filling the empty cell:\n', test['electrical'].value_counts())

Before filling the empty cell:
 SBrkr    813
FuseA     48
FuseF     15
FuseP      1
Name: electrical, dtype: int64

After filling the empty cell:
 SBrkr    814
FuseA     48
FuseF     15
FuseP      1
Name: electrical, dtype: int64


#### Checking the changed columns to ensure the values and datatypes are changed correctly and no duplicate values

##### lot_frontage column

In [12]:
#change nan values to 0
print(np.unique(test['lot_frontage']))

test['lot_frontage'].dtypes

[  0.  21.  24.  28.  30.  31.  32.  33.  34.  35.  36.  37.  39.  40.
  41.  42.  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.
  55.  56.  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.
  69.  70.  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.
  83.  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.
  97.  98.  99. 100. 101. 102. 103. 104. 105. 106. 107. 108. 110. 112.
 113. 114. 115. 116. 118. 120. 121. 122. 124. 126. 130. 131. 133. 136.
 149. 150. 152. 160. 168. 174. 182.]


dtype('float64')

##### alley column

In [13]:
#change NA values to 'no'
print(np.unique(test['alley']))

test['alley'].dtypes

['Grvl' 'Pave' 'no']


dtype('O')

##### mas_vnr_area column

In [14]:
#changed empty cells to 0
print(np.unique(test['mas_vnr_area']))

test['mas_vnr_area'].dtypes

[   0.   11.   14.   16.   18.   20.   23.   32.   34.   44.   45.   48.
   50.   51.   52.   53.   54.   58.   60.   65.   66.   67.   68.   70.
   72.   74.   75.   76.   80.   81.   82.   84.   85.   88.   89.   90.
   91.   94.   95.   96.   98.   99.  100.  101.  104.  106.  108.  112.
  113.  114.  115.  116.  117.  120.  123.  128.  130.  134.  136.  137.
  140.  141.  142.  143.  144.  145.  147.  149.  150.  151.  153.  156.
  161.  162.  164.  166.  169.  170.  171.  172.  174.  175.  176.  178.
  180.  182.  187.  188.  189.  190.  194.  196.  198.  200.  203.  205.
  206.  207.  208.  209.  212.  215.  216.  217.  218.  220.  223.  226.
  227.  229.  230.  232.  233.  236.  238.  240.  246.  247.  248.  250.
  252.  256.  258.  259.  260.  261.  263.  264.  265.  266.  268.  270.
  280.  281.  284.  285.  286.  287.  288.  293.  295.  297.  300.  302.
  304.  305.  306.  308.  310.  312.  318.  320.  328.  340.  342.  350.
  352.  356.  359.  360.  362.  364.  366.  368.  3

dtype('float64')

##### bsmt_qual, bsmt_cond, bsmtfin_type_1, bsmtfin_type_2 columns

In [15]:
#changed empty cells to 'no'

print(np.unique(test['bsmt_qual']))
print(np.unique(test['bsmt_cond']))
print(np.unique(test['bsmtfin_type_1']))
print(np.unique(test['bsmtfin_type_2']))

test[['bsmt_qual', 'bsmt_cond', 'bsmtfin_type_1', 'bsmtfin_type_2']].dtypes

['Ex' 'Fa' 'Gd' 'Po' 'TA' 'no']
['Fa' 'Gd' 'TA' 'no']
['ALQ' 'BLQ' 'GLQ' 'LwQ' 'Rec' 'Unf' 'no']
['ALQ' 'BLQ' 'GLQ' 'LwQ' 'Rec' 'Unf' 'no']


bsmt_qual         object
bsmt_cond         object
bsmtfin_type_1    object
bsmtfin_type_2    object
dtype: object

##### bsmt_fin_sf_1, bsmtfin_sf_2 columns

In [16]:
#changed empty cells to 0
print('bsmtfin_sf_1\n', np.unique(test['bsmtfin_sf_1']))
print('\nbsmtfin_sf_2\n', np.unique(test['bsmtfin_sf_2']))

test[['bsmtfin_sf_1', 'bsmtfin_sf_2']].dtypes

bsmtfin_sf_1
 [   0   16   20   24   28   33   36   40   48   49   53   54   60   68
   70   73   75   77   80  104  110  114  116  119  120  121  122  125
  144  148  150  152  154  156  165  168  169  173  175  176  180  182
  185  187  188  190  192  194  196  197  203  204  210  212  216  218
  220  224  225  231  236  238  241  248  249  250  251  252  256  257
  260  262  267  271  276  278  280  281  283  284  288  292  294  297
  299  300  301  306  308  309  310  311  315  316  317  320  322  324
  329  331  332  334  336  337  338  339  340  341  343  346  347  351
  352  353  354  356  360  366  370  371  372  374  375  378  379  380
  381  383  384  387  388  390  397  399  400  402  403  404  405  406
  408  412  414  415  420  421  426  427  428  435  438  439  442  445
  450  454  455  456  457  459  460  462  466  468  471  472  474  480
  483  484  486  489  490  491  493  498  500  502  503  504  505  509
  512  513  515  518  520  521  523  524  528  536  539  540  5

bsmtfin_sf_1    int64
bsmtfin_sf_2    int64
dtype: object

##### fireplace_qu column

In [17]:
#change NA to 'no'
print(np.unique(test['fireplace_qu']))

test['fireplace_qu'].dtypes

['Ex' 'Fa' 'Gd' 'Po' 'TA' 'no']


dtype('O')

##### garage_type, garage_finish, garage_qual, garage_cond columns

In [18]:
#change NA and empty cells to 'no'
print(np.unique(test['garage_type']))
print(np.unique(test['garage_finish']))
print(np.unique(test['garage_qual']))
print(np.unique(test['garage_cond']))

test[['garage_type', 'garage_finish', 'garage_qual', 'garage_cond']].dtypes

['2Types' 'Attchd' 'Basment' 'BuiltIn' 'CarPort' 'Detchd' 'no']
['Fin' 'RFn' 'Unf' 'no']
['Fa' 'Gd' 'Po' 'TA' 'no']
['Ex' 'Fa' 'Gd' 'Po' 'TA' 'no']


garage_type      object
garage_finish    object
garage_qual      object
garage_cond      object
dtype: object

##### pool_qc, fence, misc_feature columns

In [19]:
#change the NA cells to 'no'
print(np.unique(test['pool_qc']))
print(np.unique(test['fence']))
print(np.unique(test['misc_feature']))

test[['pool_qc', 'fence', 'misc_feature']].dtypes

['Ex' 'TA' 'no']
['GdPrv' 'GdWo' 'MnPrv' 'MnWw' 'no']
['Gar2' 'Othr' 'Shed' 'no']


pool_qc         object
fence           object
misc_feature    object
dtype: object

#### Modify remaining columns for standardisation and switching to binary

##### msr_vnr_type column 

In [20]:
#change "None" to 'no' to standardise values
test['mas_vnr_type'] = test['mas_vnr_type'].replace('None', 'no')

print(np.unique(test['mas_vnr_type']))

test['mas_vnr_type'].dtypes

['BrkCmn' 'BrkFace' 'CBlock' 'Stone' 'no']


dtype('O')

##### bsmt_exposure column

In [21]:
#bsmt_exposure change 'No' to 'NE' to indicate that there is basement but no exposure
#differentiate it from the NA cells that were changed to 'no' where it means there is no basement at all
test['bsmt_exposure'] = test['bsmt_exposure'].replace('No', 'NE')

print(np.unique(test['bsmt_exposure']))

test['bsmt_exposure'].dtypes

['Av' 'Gd' 'Mn' 'NE' 'no']


dtype('O')

##### central_air column

In [22]:
#central_air contains Y and N, change it to binary so we don't need to dummify this column
print('original central_air values: ', np.unique(test['central_air']))

original central_air values:  ['N' 'Y']


In [23]:
# Y change to 1
# N change to 0
test['central_air'] = test['central_air'].replace(['Y', 'N'], [1, 0])

print('central_air values after changing: ', np.unique(test['central_air']))
test['central_air'].dtypes

central_air values after changing:  [0 1]


dtype('int64')

#### Check for other issues with data and edit

check all other columns for any values that need to change by running the np.unique() function

only those with issues are left here to display as part of showing the cleaning process

In [24]:
print('orignal values:\n', np.unique(test['ms_zoning']))

#ms_zoning column to remove space and brackets from cell values
test['ms_zoning'] = test['ms_zoning'].apply(lambda value: value.replace(value, value[0]) if ' ' in value else value)

print('\nvalues after changing:\n', np.unique(test['ms_zoning']))

orignal values:
 ['C (all)' 'FV' 'I (all)' 'RH' 'RL' 'RM']

values after changing:
 ['C' 'FV' 'I' 'RH' 'RL' 'RM']


In [25]:
print('orignal values:\n', np.unique(test['exterior_1st']))

#exterior_1st column to remove spacing from cell values
test['exterior_1st'] = test['exterior_1st'].apply(lambda value: value.replace(' ', '_') if ' ' in value else value)

print('\nvalues after changing:\n', np.unique(test['exterior_1st']))

orignal values:
 ['AsbShng' 'AsphShn' 'BrkComm' 'BrkFace' 'CemntBd' 'HdBoard' 'MetalSd'
 'Plywood' 'PreCast' 'Stucco' 'VinylSd' 'Wd Sdng' 'WdShing']

values after changing:
 ['AsbShng' 'AsphShn' 'BrkComm' 'BrkFace' 'CemntBd' 'HdBoard' 'MetalSd'
 'Plywood' 'PreCast' 'Stucco' 'VinylSd' 'WdShing' 'Wd_Sdng']


In [26]:
print('orignal values:\n', np.unique(test['exterior_2nd']))

#exterior_2nd column to remove spacing from cell values
test['exterior_2nd'] = test['exterior_2nd'].apply(lambda value: value.replace(' ', '_') if ' ' in value else value)

print('\nvalues after changing:\n', np.unique(test['exterior_2nd']))

orignal values:
 ['AsbShng' 'AsphShn' 'Brk Cmn' 'BrkFace' 'CBlock' 'CmentBd' 'HdBoard'
 'ImStucc' 'MetalSd' 'Other' 'Plywood' 'PreCast' 'Stucco' 'VinylSd'
 'Wd Sdng' 'Wd Shng']

values after changing:
 ['AsbShng' 'AsphShn' 'BrkFace' 'Brk_Cmn' 'CBlock' 'CmentBd' 'HdBoard'
 'ImStucc' 'MetalSd' 'Other' 'Plywood' 'PreCast' 'Stucco' 'VinylSd'
 'Wd_Sdng' 'Wd_Shng']


#### Drop columns:
pid <br>
gr_living_area <br>
garage_yr_blt

In [27]:
#dropping pid column as it does not serve any purpose in the model since we will use the id to reference each house

#dropping gr_liv_area column since:   gr_liv_area  =  1st_flr_sf  +  2nd_flr_sf  +  low_qual_fin_sf
#keeping the other 3 columns, drop gr_liv_area to reduce multicollinearity

#dropping garage_yr_built column as building a garage is considered remodelling the house
#it is included in year_remod/add

test = test.drop(columns=['pid', 'gr_liv_area', 'garage_yr_blt'])

print(test.shape)
list(test.columns)

(878, 77)


['id',
 'ms_subclass',
 'ms_zoning',
 'lot_frontage',
 'lot_area',
 'street',
 'alley',
 'lot_shape',
 'land_contour',
 'utilities',
 'lot_config',
 'land_slope',
 'neighborhood',
 'condition_1',
 'condition_2',
 'bldg_type',
 'house_style',
 'overall_qual',
 'overall_cond',
 'year_built',
 'year_remod/add',
 'roof_style',
 'roof_matl',
 'exterior_1st',
 'exterior_2nd',
 'mas_vnr_type',
 'mas_vnr_area',
 'exter_qual',
 'exter_cond',
 'foundation',
 'bsmt_qual',
 'bsmt_cond',
 'bsmt_exposure',
 'bsmtfin_type_1',
 'bsmtfin_sf_1',
 'bsmtfin_type_2',
 'bsmtfin_sf_2',
 'bsmt_unf_sf',
 'total_bsmt_sf',
 'heating',
 'heating_qc',
 'central_air',
 'electrical',
 '1st_flr_sf',
 '2nd_flr_sf',
 'low_qual_fin_sf',
 'bsmt_full_bath',
 'bsmt_half_bath',
 'full_bath',
 'half_bath',
 'bedroom_abvgr',
 'kitchen_abvgr',
 'kitchen_qual',
 'totrms_abvgrd',
 'functional',
 'fireplaces',
 'fireplace_qu',
 'garage_type',
 'garage_finish',
 'garage_cars',
 'garage_area',
 'garage_qual',
 'garage_cond',
 'pave

#### Changing rating system to numerical format

In [28]:
#change the columns with rating systems into numerical format to avoid dummification

#exter_qual
#exter_cond
#bsmt_qual
#bsmt_cond
#heating_qc
#kitchen_qual
#fireplace_qu
#garage_qual
#garage_cond
#pool_qc

test['exter_qual'] = test['exter_qual'].replace({
    'Ex': 5, 
    'Gd': 4, 
    'TA': 3, 
    'Fa': 2, 
    'Po': 1})

test['exter_cond'] = test['exter_cond'].replace({
    'Ex': 5, 
    'Gd': 4, 
    'TA': 3, 
    'Fa': 2, 
    'Po': 1})

test['bsmt_qual'] = test['bsmt_qual'].replace({
    'Ex': 5, 
    'Gd': 4, 
    'TA': 3, 
    'Fa': 2, 
    'Po': 1, 
    'no': 0
})

test['bsmt_cond'] = test['bsmt_cond'].replace({
    'Ex': 5, 
    'Gd': 4, 
    'TA': 3, 
    'Fa': 2, 
    'Po': 1, 
    'no': 0
})

test['heating_qc'] = test['heating_qc'].replace({
    'Ex': 5, 
    'Gd': 4, 
    'TA': 3, 
    'Fa': 2, 
    'Po': 1
})

test['kitchen_qual'] = test['kitchen_qual'].replace({
    'Ex': 5, 
    'Gd': 4, 
    'TA': 3, 
    'Fa': 2, 
    'Po': 1
})

test['fireplace_qu'] = test['fireplace_qu'].replace({
    'Ex': 5, 
    'Gd': 4, 
    'TA': 3, 
    'Fa': 2, 
    'Po': 1, 
    'no': 0
})

test['garage_qual'] = test['garage_qual'].replace({
    'Ex': 5, 
    'Gd': 4, 
    'TA': 3, 
    'Fa': 2, 
    'Po': 1, 
    'no': 0
})

test['garage_cond'] = test['garage_cond'].replace({
    'Ex': 5, 
    'Gd': 4, 
    'TA': 3, 
    'Fa': 2, 
    'Po': 1, 
    'no': 0
})

test['pool_qc'] = test['pool_qc'].replace({
    'Ex': 5, 
    'Gd': 4, 
    'TA': 3, 
    'Fa': 2,
    'no': 0
})

In [29]:
#show the changes
print(np.unique(test['exter_qual']))
print(np.unique(test['exter_cond']))
print(np.unique(test['bsmt_qual']))
print(np.unique(test['bsmt_cond']))
print(np.unique(test['heating_qc']))
print(np.unique(test['kitchen_qual']))
print(np.unique(test['fireplace_qu']))
print(np.unique(test['garage_qual']))
print(np.unique(test['garage_cond']))
print(np.unique(test['pool_qc']))

[2 3 4 5]
[1 2 3 4 5]
[0 1 2 3 4 5]
[0 2 3 4]
[2 3 4 5]
[1 2 3 4 5]
[0 1 2 3 4 5]
[0 1 2 3 4]
[0 1 2 3 4 5]
[0 3 5]


In [30]:
#change the columns with rating systems into numerical format to avoid dummification

#lot_shape
#bsmt_exposure
#utilities
#bsmtfin_type_1
#bsmtfin_type_2
#functional
#garage_finish
#paved_drive

test['lot_shape'] = test['lot_shape'].replace({
    'Reg': 4, 
    'IR1': 3, 
    'IR2': 2, 
    'IR3': 1
})

test['bsmt_exposure'] = test['bsmt_exposure'].replace({
    'Av': 3, 
    'Gd': 2, 
    'Mn': 1, 
    'NE': 0, 
    'no': 0
})

test['utilities'] = test['utilities'].replace({
    'AllPub': 4, 
    'NoSewr': 3, 
    'NoSeWa': 2, 
    'ELO': 1
})

test['bsmtfin_type_1'] = test['bsmtfin_type_1'].replace({
    'GLQ': 6, 
    'ALQ': 5, 
    'BLQ': 4, 
    'Rec': 3,
    'LwQ': 2, 
    'Unf': 1, 
    'no': 0
})

test['bsmtfin_type_2'] = test['bsmtfin_type_2'].replace({
    'GLQ': 6, 
    'ALQ': 5, 
    'BLQ': 4, 
    'Rec': 3,
    'LwQ': 2, 
    'Unf': 1, 
    'no': 0
})

test['functional'] = test['functional'].replace({
    'Typ': 8, 
    'Min1': 7, 
    'Min2': 6, 
    'Mod': 5, 
    'Maj1': 4,
    'Maj2': 3, 
    'Sev': 2, 
    'Sal': 1
})

test['garage_finish'] = test['garage_finish'].replace({
    'Fin': 3, 
    'RFn': 2, 
    'Unf': 1, 
    'no': 0
})

test['paved_drive'] = test['paved_drive'].replace({
    'Y': 2, 
    'P': 1, 
    'N': 0
})

In [31]:
#show the changes
print(np.unique(test['lot_shape']))
print(np.unique(test['bsmt_exposure']))
print(np.unique(test['utilities']))
print(np.unique(test['bsmtfin_type_1']))
print(np.unique(test['bsmtfin_type_2']))
print(np.unique(test['functional']))
print(np.unique(test['garage_finish']))
print(np.unique(test['paved_drive']))

[1 2 3 4]
[0 1 2 3]
[3 4]
[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6]
[3 4 5 6 7 8]
[0 1 2 3]
[0 1 2]


## Export cleaned dataframe into CSV file

In [32]:
test.to_csv('../data/test_cleaned.csv', index=False)

## Import cleaned CSV file 

In [33]:
test_clean = pd.read_csv('../data/test_cleaned.csv')

test_clean.head()

id  ms_subclass ms_zoning  lot_frontage  lot_area street alley  \
0  2658          190        RM          69.0      9142   Pave  Grvl   
1  2718           90        RL           0.0      9662   Pave    no   
2  2414           60        RL          58.0     17104   Pave    no   
3  1989           30        RM          60.0      8520   Pave    no   
4   625           20        RL           0.0      9500   Pave    no   

   lot_shape land_contour  utilities lot_config land_slope neighborhood  \
0          4          Lvl          4     Inside        Gtl      OldTown   
1          3          Lvl          4     Inside        Gtl       Sawyer   
2          3          Lvl          4     Inside        Gtl      Gilbert   
3          4          Lvl          4     Inside        Gtl      OldTown   
4          3          Lvl          4     Inside        Gtl        NAmes   

  condition_1 condition_2 bldg_type house_style  overall_qual  overall_cond  \
0        Norm        Norm    2fmCon      2Story             6             8   
1        Norm        Norm    Duplex      1Story             5             4   
2        Norm        Norm      1Fam      2Story             7             5   
3        Norm        Norm      1Fam      1Story             5             6   
4        Norm        Norm      1Fam      1Story             6             5   

   year_built  year_remod/add roof_style roof_matl exterior_1st exterior_2nd  \
0        1910            1950      Gable   CompShg      AsbShng      AsbShng   
1        1977            1977      Gable   CompShg      Plywood      Plywood   
2        2006            2006      Gable   CompShg      VinylSd      VinylSd   
3        1923            2006      Gable   CompShg      Wd_Sdng      Wd_Sdng   
4        1963            1963      Gable   CompShg      Plywood      Plywood   

  mas_vnr_type  mas_vnr_area  exter_qual  exter_cond foundation  bsmt_qual  \
0           no           0.0           3           2      Stone          2   
1           no           0.0           3           3     CBlock          4   
2           no           0.0           4           3      PConc          4   
3           no           0.0           4           3     CBlock          3   
4      BrkFace         247.0           3           3     CBlock          4   

   bsmt_cond  bsmt_exposure  bsmtfin_type_1  bsmtfin_sf_1  bsmtfin_type_2  \
0          3              0               1             0               1   
1          3              0               1             0               1   
2          4              3               6           554               1   
3          3              0               1             0               1   
4          3              0               4           609               1   

   bsmtfin_sf_2  bsmt_unf_sf  total_bsmt_sf heating  heating_qc  central_air  \
0             0         1020           1020    GasA           4            0   
1             0         1967           1967    GasA           3            1   
2             0          100            654    GasA           5            1   
3             0          968            968    GasA           3            1   
4             0          785           1394    GasA           4            1   

  electrical  1st_flr_sf  2nd_flr_sf  low_qual_fin_sf  bsmt_full_bath  \
0      FuseP         908        1020                0               0   
1      SBrkr        1967           0                0               0   
2      SBrkr         664         832                0               1   
3      SBrkr         968           0                0               0   
4      SBrkr        1394           0                0               1   

   bsmt_half_bath  full_bath  half_bath  bedroom_abvgr  kitchen_abvgr  \
0               0          2          0              4              2   
1               0          2          0              6              2   
2               0          2          1              3              1   
3               0          

## Dummify columns

In [34]:
test_clean = pd.get_dummies(columns=['ms_subclass', 
                                      'ms_zoning', 
                                      'street', 
                                      'alley', 
                                      'land_contour', 
                                      'lot_config', 
                                      'land_slope', 
                                      'neighborhood', 
                                      'condition_1', 
                                      'condition_2', 
                                      'bldg_type', 
                                      'house_style', 
                                      'roof_style', 
                                      'roof_matl', 
                                      'exterior_1st', 
                                      'exterior_2nd', 
                                      'mas_vnr_type', 
                                      'foundation', 
                                      'heating', 
                                      'electrical', 
                                      'garage_type', 
                                      'fence', 
                                      'misc_feature', 
                                      'sale_type'], 
                             drop_first=True, data=test_clean)


In [35]:
print(test_clean.shape)
list(test_clean)

(878, 204)


['id',
 'lot_frontage',
 'lot_area',
 'lot_shape',
 'utilities',
 'overall_qual',
 'overall_cond',
 'year_built',
 'year_remod/add',
 'mas_vnr_area',
 'exter_qual',
 'exter_cond',
 'bsmt_qual',
 'bsmt_cond',
 'bsmt_exposure',
 'bsmtfin_type_1',
 'bsmtfin_sf_1',
 'bsmtfin_type_2',
 'bsmtfin_sf_2',
 'bsmt_unf_sf',
 'total_bsmt_sf',
 'heating_qc',
 'central_air',
 '1st_flr_sf',
 '2nd_flr_sf',
 'low_qual_fin_sf',
 'bsmt_full_bath',
 'bsmt_half_bath',
 'full_bath',
 'half_bath',
 'bedroom_abvgr',
 'kitchen_abvgr',
 'kitchen_qual',
 'totrms_abvgrd',
 'functional',
 'fireplaces',
 'fireplace_qu',
 'garage_finish',
 'garage_cars',
 'garage_area',
 'garage_qual',
 'garage_cond',
 'paved_drive',
 'wood_deck_sf',
 'open_porch_sf',
 'enclosed_porch',
 '3ssn_porch',
 'screen_porch',
 'pool_area',
 'pool_qc',
 'misc_val',
 'mo_sold',
 'yr_sold',
 'ms_subclass_30',
 'ms_subclass_40',
 'ms_subclass_45',
 'ms_subclass_50',
 'ms_subclass_60',
 'ms_subclass_70',
 'ms_subclass_75',
 'ms_subclass_80',
 'ms

## Export dummified dataframe into CSV file

In [36]:
test_clean.to_csv('../data/test_cleaned_dummified.csv', index=False)